apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: mtharrison/microservices-ci-cd-example-api:{{ .Values.imageVersion }}
        ports:
        - containerPort: 8000
        env:
        - name: CLIENT_ID
          value: "{{ .Values.CLIENT_ID }}"
        - name: CLIENT_SECRET
          value: "{{ .Values.CLIENT_SECRET }}"
        - name: ACCESS_TOKEN
          value: "{{ .Values.ACCESS_TOKEN }}"
        - name: REFRESH_TOKEN
          value: "{{ .Values.REFRESH_TOKEN }}"
        - name: HUE_USERNAME
          value: "{{ .Values.HUE_USERNAME }}"

        - name: GH_CLIENT_ID
          value: "{{ .Values.GH_CLIENT_ID }}"
        - name: GH_CLIENT_SECRET
          value: "{{ .Values.GH_CLIENT_SECRET }}"
        - name: ALLOWED_USERS
          value: "{{ .Values.ALLOWED_USERS }}"
        - name: JWT_SECRET
          value: "{{ .Values.JWT_SECRET }}"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
